- name: Add Kafka topic for the component
  command: /opt/DataLake/kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 2 --partitions 1 --topic {{ comp_kafka_topic }}
  ignore_errors: yes
