CREATE TABLE ADMISSIONTYPES (
  ADMTYPEDBOID NUMERIC(21) PRIMARY KEY,
  ADMTYPEDESC  VARCHAR(218),
  ISDELETED    VARCHAR(1)
);
GO
CREATE TABLE CURRENTMEDICATIONSTATUS (
  CURRENTMEDICATIONSTATUSDBOID NUMERIC(21) PRIMARY KEY,
  CURRENTMEDICATIONSTATUSDESC  VARCHAR(255),
  ISDELETED                    VARCHAR(1),
  CURRENTMEDICATIONSTATUSINDEX NUMERIC(3)
);
GO
CREATE TABLE PCS_EVENTDATA (
  STARTED           DATETIME,
  PICISDATADBOID    NUMERIC(21),
  EVENTDBOID        NUMERIC(21),
  STAFFDBOID        NUMERIC(21),
  LOCATIONDBOID     NUMERIC(21),
  APPLICATIONDBOID  NUMERIC(21),
  PCSEVENTDATADBOID NUMERIC(21) PRIMARY KEY,
  PCSEVENTDATADESC  VARCHAR(255)
);
GO
INSERT INTO ADMISSIONTYPES (ADMTYPEDBOID, ADMTYPEDESC, ISDELETED) VALUES (1,'TEST1','N');
INSERT INTO ADMISSIONTYPES (ADMTYPEDBOID, ADMTYPEDESC, ISDELETED) VALUES (2,'TEST2','N');
GO
INSERT INTO CURRENTMEDICATIONSTATUS (CURRENTMEDICATIONSTATUSDBOID, CURRENTMEDICATIONSTATUSDESC, ISDELETED, CURRENTMEDICATIONSTATUSINDEX) VALUES (1,'MEDICATION TEST1','N',1);
INSERT INTO CURRENTMEDICATIONSTATUS (CURRENTMEDICATIONSTATUSDBOID, CURRENTMEDICATIONSTATUSDESC, ISDELETED, CURRENTMEDICATIONSTATUSINDEX) VALUES (2,'MEDICATION TEST2','N',1);
GO
INSERT INTO PCS_EVENTDATA (STARTED, PICISDATADBOID, EVENTDBOID, STAFFDBOID, LOCATIONDBOID, APPLICATIONDBOID, PCSEVENTDATADBOID, PCSEVENTDATADESC) VALUES ('12-12-2016',1,2,3,4,5,6,'PC DESC');
INSERT INTO PCS_EVENTDATA (STARTED, PICISDATADBOID, EVENTDBOID, STAFFDBOID, LOCATIONDBOID, APPLICATIONDBOID, PCSEVENTDATADBOID, PCSEVENTDATADESC) VALUES ('11-11-2016',7,8,9,10,11,12,'PC DESC2');
GO
CREATE TABLE caresuite_integration_parameters (caresuite_table_name VARCHAR(255),key_column varchar(255),
                                               parameter_type VARCHAR(20),time_column VARCHAR(255),last_used_value NUMERIC(21),changed DATETIME);
GO
INSERT INTO caresuite_integration_parameters(caresuite_table_name, key_column, parameter_type, time_column, last_used_value, changed)
values ('ADMISSIONTYPES','ADMTYPEDBOID','FULL_TABLE',null,null,null);
INSERT INTO caresuite_integration_parameters (caresuite_table_name, key_column, parameter_type, time_column, last_used_value, changed) VALUES
  ('CURRENTMEDICATIONSTATUS','CURRENTMEDICATIONSTATUSDBOID','HISTORY_TABLE_LOOKUP',null,1,null);
INSERT INTO caresuite_integration_parameters(caresuite_table_name, key_column, parameter_type, time_column, last_used_value, changed) VALUES
  ('PCS_EVENTDATA','PCSEVENTDATADBOID','TIME_COMPARISATION','STARTED',null,'01-01-01');
GO



